title: Kaushik Ghosh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p style="font-size:13px"> <br>BE, Information Technology, School of Information Technology, West Bengal University of Technology ||
  MBA, Vinod Gupta School of Management, Indian Institute of Technology, IIT Khragpur<br>
  <br>Author of various papers at many internationally published journals including top Business Schools of the globe ||
  Peer Reviewer ||
  Public Policy Analyst and Researcher || 
  Finance Enthusiast || 
  Subject Expert of Economics, Mathematics and Finance on various online platforms ||
  Mentor for Civil Services preparation || 
  Gazetted Officer, Ministry of Defence, Govt of India <font> </p>
  
  <br> <a href="https://www.linkedin.com/in/kaushik-ghosh-bb3a2430/">View My LinkedIn Profile</a> <br> 
  <a href="https://hq.ssrn.com/submissions/MyPapers.cfm?partid=4021364">View My SSRN Page</a> 
# theme: jekyll-theme-leap-day
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

theme: jekyll-theme-minimal
