title: Kaushik Ghosh # your name (or website title) here
logo: "https://github.com/kaus2007/cv/blob/master/images/Kaushik%20Formal.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>MBA, Public Policy Analyst and Researcher<br>
  Second description 
  <br>Finance Enthusiast<br>
  <a href="https://www.linkedin.com/in/kaushik-ghosh-bb3a2430/">View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-leap-day
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
